MvcWebRole1/Controllers/DareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HowMuchTo.Models;

namespace HowMuchTo.Controllers
{
    public class DareController : Controller
    {
        //
        // GET: /Dare/

        public ActionResult Index()
        {
            return Latest();
        }

        public ActionResult Show(long id)
        {
            Challenge c = RepoFactory.GetChallengeRepo().Get(id);

            c.Customer = RepoFactory.GetCustomerRepo().GetWithID(c.CustomerID);
            
            if(c.TargetCustomerID!=0)
                c.TargetCustomer = RepoFactory.GetCustomerRepo().GetWithID(c.TargetCustomerID);
            
            c.Bids = RepoFactory.GetChallengeBidRepo().Get(c.ID);

            return View(c);
        }

        public ActionResult Latest()
        {
            IEnumerable<Challenge> c = RepoFactory.GetChallengeRepo().GetNewest(0, 10);
            return View(c);
        }
    }
}

MvcWebRole1/Controllers/OnboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TweetSharp;
using HowMuchTo.Models;
using Facebook;
using Twilio;
using Stripe;

namespace HowMuchTo.Controllers
{
    public class OnboardController : Controller
    {
        public class TextLinkInfo
        {
            public string PhoneNumber { get; set; }
        }

        FacebookClient _fb;
        OnboardManager _obm;
        DareManager _dmgr;

        public OnboardController()
        {
            _fb = new FacebookClient();
            _obm = new OnboardManager();
            _dmgr = new DareManager();
        }

        //
        // GET: /Onboard/
        private const string _twitterAuthKey = "zb8BkscTtBjr5oyALIUHig";
        private const string _twitterConsumerSecret = "bqsUpg4JyCM3a9pW9Q5m8SY9eGjtySwOrIfSyEipY";

        private const string _fbAppID = "309260905814607";
        private const string _fbAppSecret = "c8c000c0ef5e4adc6a760662cd37638b";
        private const string _fbRedirectUrl = "https://api.dareme.to/Onboard/CompleteFacebook/";

        public ActionResult Index()
        {
            return View();
        }

        private void SafeUpdateOnboardToken(OnboardToken tok)
        {
            // only allows the updating of the email address, first name and last name fields

            OnboardToken updateToken = new OnboardToken();
            updateToken.CustomerID = tok.CustomerID;
            updateToken.VerificationString = tok.VerificationString;

            updateToken.FirstName = tok.FirstName;
            updateToken.LastName = tok.LastName;
            updateToken.EmailAddress = tok.EmailAddress;

            RepoFactory.GetOnboardTokenRepo().Update(updateToken);
        }

        [HttpGet]
        public ActionResult AuthorizeFacebook()
        {
            var redirectUri=_fb.GetLoginUrl(new { 
                client_id=_fbAppID,
                client_secret=_fbAppSecret,
                redirect_uri=_fbRedirectUrl,
                response_type="code",
                scope="",
                state=System.Guid.NewGuid().ToString()
            });

            return Redirect(redirectUri.AbsoluteUri);
        }

        [HttpGet]
        public ActionResult AuthorizeTwitter()
        {
            TwitterService service = new TwitterService(_twitterAuthKey, _twitterConsumerSecret);

            string redirectUri;

            redirectUri = "https://api.dareme.to/Onboard/CompleteTwitter/";
            
            OAuthRequestToken requestToken = service.GetRequestToken(redirectUri);

            Uri uri = service.GetAuthorizationUri(requestToken);
            return new RedirectResult(uri.ToString(), false);
        }

        public ActionResult CompleteFacebook(string code, string state)
        {
            dynamic result = _fb.Post("oauth/access_token",
                                        new { 
                                            client_id=_fbAppID,
                                            client_secret=_fbAppSecret,
                                            redirect_uri = _fbRedirectUrl,
                                            code=code
                                        });

            string fbAccessToken = result.access_token;

            _fb.AccessToken = result.access_token;
            _fb.AppId = _fbAppID;
            _fb.AppSecret = _fbAppSecret;

            dynamic meResponse=_fb.Get("me");
            string fbID = meResponse.id;

            OnboardResult r = _obm.CompleteFirstStepForeignUserOnboard(fbID, Customer.ForeignUserTypes.Facebook, _fb.AccessToken);

            if (r == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);

            if (r.Customer.Type != (int)Customer.TypeCodes.Unclaimed)
            {
                return View("AlreadyACustomer");
            }
            else
            {
                r.OnboardToken.FirstName = meResponse.first_name;
                r.OnboardToken.LastName = meResponse.last_name;

                r.OnboardToken.Secret = null;
                return View("CompleteOnboard", r.OnboardToken);
            }
        }

        /*
        private OnboardResult CoreCompleteFirstStepForeignUserOnboard(string handle, Customer.ForeignUserTypes type, string token=null, string tokenSecret=null)
        {
            OnboardResult r = new OnboardResult();

            Customer c = RepoFactory.GetCustomerRepo().GetWithForeignUserID(handle, type);

            if (c == null)
            {
                Customer newCust = new Customer()
                {
                    ForeignUserID = handle,
                    ForeignUserType = (int)type,
                    Type = (int)Customer.TypeCodes.Unclaimed,
                    BillingType = (int)BillingSystem.BillingProcessorFactory.SupportedBillingProcessor.Stripe
                };

                newCust.ID = RepoFactory.GetCustomerRepo().Add(newCust);

                RepoFactory.GetCustomerRepo().AddForeignNetworkForCustomer(newCust.ID, handle, type);

                r.Customer = newCust;
            }
            else
            {
                // we don't put this in the repo, we're just
                // using it as a DTO to get the token and secret
                // back to the controller
                r.Customer = c;
            }

            OnboardToken newToken = new OnboardToken()
            {
                CustomerID = r.Customer.ID,
                VerificationString = System.Guid.NewGuid().ToString(),
                Token = token,
                Secret = tokenSecret,
                AccountType = (int)type,
                ForeignUserID = handle
            };

            RepoFactory.GetOnboardTokenRepo().Add(newToken);

            r.OnboardToken = newToken;

            return r;
        }
        */

        private OnboardResult CoreCompleteTwitter(string oauth_token, string oauth_verifier)
        {
            OnboardResult r=new OnboardResult();

            var requestToken = new OAuthRequestToken { Token = oauth_token };

            TwitterService service = new TwitterService(_twitterAuthKey, _twitterConsumerSecret);
            OAuthAccessToken accessToken = service.GetAccessToken(requestToken, oauth_verifier);
            
            service.AuthenticateWith(accessToken.Token, accessToken.TokenSecret);
            TwitterUser user = service.VerifyCredentials();

            string handle = "@"+user.ScreenName;

            if (handle == null || handle.Equals(""))
                return null;

            return _obm.CompleteFirstStepForeignUserOnboard(handle, Customer.ForeignUserTypes.Twitter, accessToken.Token, accessToken.TokenSecret);
        }

        public ActionResult CompleteTwitter(string oauth_token, string oauth_verifier)
        {
            OnboardResult r = CoreCompleteTwitter(oauth_token, oauth_verifier);

            if (r == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);

            if (r.Customer.Type != (int)Customer.TypeCodes.Unclaimed)
            {
                return View("AlreadyACustomer");
            }
            else
            {
                r.OnboardToken.Secret = null;
                return View("CompleteOnboard", r.OnboardToken);
            }
        }

        public ActionResult StartSignup(long ChallengeID=0, int DoBilling=0)
        {
            OnboardToken token = new OnboardToken();
            token.ChallengeID = ChallengeID;
            if (DoBilling == 1)
                token.AccountType = 1;

            return View("StartSignup", token);
        }
        
        [HttpPost]
        public ActionResult BillingOnboard(OnboardToken token)
        {
            OnboardToken retrievedToken = RepoFactory.GetOnboardTokenRepo().Get(token.VerificationString);

            Customer cust = RepoFactory.GetCustomerRepo().GetWithID(retrievedToken.CustomerID);

            // hardcode stripe for now, sucka
            StripeClient client = new StripeClient("LB3kUwdhiUlPlNl1UYW52NLn4q88QsFT");
            Stripe.CreditCardToken ccToken = new Stripe.CreditCardToken(token.BillingID);
            var stripeCustomer = client.CreateCustomer(ccToken, email: cust.EmailAddress);
            
            cust.BillingType = (int)BillingSystem.BillingProcessorFactory.SupportedBillingProcessor.Stripe;
            cust.BillingID = stripeCustomer.GetProperty("ID").ToString();

            RepoFactory.GetCustomerRepo().Update(cust);

            CustomerController.CustomerSignupResult result = new CustomerController.CustomerSignupResult();
            result.Result = CustomerController.CustomerSignupResult.ResultCode.Success;
            result.Customer = cust;

            if (retrievedToken.ChallengeID != 0)
            {
                Security s = new Security();
                Authorization a=s.AuthorizeCustomer(new Login { EmailAddress = cust.EmailAddress, Password = cust.Password });
                return Redirect("http://dareme.to/authorize?id="+a.CustomerID.ToString()+"&session_token="+a.Token+"&dare=" + retrievedToken.ChallengeID.ToString());
            }
            else
            {
                return View("SignupComplete", result);
            }
        }

        [HttpPost]
        public ActionResult Signup(SignupCustomer newCustomer)
        {
            CustomerController custCtl = new CustomerController();

            CustomerController.CustomerSignupResult result = custCtl.HandleCredentialSignup(newCustomer);

            if (result.Result != CustomerController.CustomerSignupResult.ResultCode.Success)
                return View("SignupFailed");


MvcWebRole1/Views/Dare/Latest.cshtml
@model IEnumerable<DareyaAPI.Models.Challenge>

@{
    ViewBag.Title = "Latest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Latest</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Privacy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Visibility)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrentBid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Anonymous)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TargetCustomerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfTakers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfBidders)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Privacy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Visibility)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentBid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Anonymous)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TargetCustomerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfTakers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfBidders)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

MvcWebRole1/Views/Dare/Show.Mobile.cshtml
@model DareyaAPI.Models.Challenge

@{
    ViewBag.Title = "dareme.to - "+Model.Description;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    #main #bountyHeader #avatar { background-image: url('@(Model.Customer.AvatarURL)'); }
</style>

		<div class="sectionHeader">Someone's been dared!</div>
		
		<div id="bountyHeader">
			<div id="avatar"></div>
            @{
                if(Model.Bids.Count>1)
                {
                    <p>@Model.Customer.FirstName and @(Model.Bids.Count - 1) others have put up</p>
                }
                else
                {
                    <p>@Model.Customer.FirstName has put up</p>
                }
            }
			
			<div id="amount">$@Model.CurrentBid.ToString("0.00", System.Globalization.CultureInfo.InvariantCulture)</div>
		</div>
		
		<div class="contentSection">
			<div id="dareDesc">@Model.Description</div>
		</div>
        
		<div class="sectionHeader">
			Want to up the ante?
		</div>
		<div class="contentSection">
            <p>Get dareme.to on the <a href="http://itunes.apple.com/us/app/dareme.to/id532840446?mt=8">iTunes App Store</a></p>
           <!-- <p>Already have dareme.to? <a href="daremeto://@(Model.ID.ToString())">Open this dare in the app.</a></p> -->
		</div>
		
		<div class="sectionHeader">
			Ready to take this dare?
			</div>
		<div class="contentSection">
            @{
                if (Model.TargetCustomer != null)
                {
                    <p>This dare is only for @(Model.TargetCustomer.FirstName). Is that you? Get connected.</p>
                    
                    switch (Model.TargetCustomer.ForeignUserType)
                    {
                        case (int)DareyaAPI.Models.Customer.ForeignUserTypes.Facebook:
                            <p>@Html.ActionLink("Authenticate with Facebook", "AuthorizeFacebook", "Onboard")</p>
                            break;
                        case (int)DareyaAPI.Models.Customer.ForeignUserTypes.Twitter:
                            <p>@Html.ActionLink("Authenticate with Twitter", "AuthorizeTwitter", "Onboard")</p>
                            break;
                    }
                }
                else
                {
                    <p>This dare is up for grabs. Get <a href="http://itunes.apple.com/us/app/dareme.to/id532840446?mt=8">dareme.to from the App Store</a> and make your attempt!</p>
                }
            }
		</div>

MvcWebRole1/Views/Dare/Show.cshtml
@model DareyaAPI.Models.Challenge

@{
    ViewBag.Title = "dareme.to - " + Model.Description;
    Layout = "~/Views/Shared/_Layout.cshtml";

    string targetFirstName;

    if (Model.TargetCustomer != null && Model.TargetCustomer.FirstName!=null && !Model.TargetCustomer.FirstName.Equals(""))
    {
        targetFirstName = Model.TargetCustomer.FirstName;
    }
    else
    {
        targetFirstName = "Someone";
    }

    string bidderDescString;
    bool plural;
    
    if(Model.NumberOfBidders>2)
    {
        bidderDescString="<strong>"+Model.Customer.FirstName+"</strong> and "+(Model.NumberOfBidders - 1).ToString()+" others";
        plural = false;
    }
    else if(Model.NumberOfBidders==2)
    {
        bidderDescString = Model.Customer.FirstName + " and 1 other";
        plural = false;
    }
    else
    {
        bidderDescString = Model.Customer.FirstName;
        plural = true;
    }
}

	<div id="left">
		<div class="sectionHeader">Latest Dares</div>
		
	</div>

<div id="content">
	<div class="sectionHeader">@{if (Model.TargetCustomer != null)
                              {
                                  @("This dare is open for " + Model.TargetCustomer.FirstName)   
                              }
                              else
                              {
                                  @("This dare is open for anyone")
                              }
                              }</div>
	
	<div id="top">
		<img id="avatar" src="@Model.Customer.AvatarURL" />
		<div id="bountycallout">@{
        if(plural)
        {
            @(bidderDescString + " has put up")
        }
        else
        {
            @(bidderDescString + " have put up")
        }
      }</div>
		<div id="bounty">$@(Model.CurrentBid.ToString("0.00", System.Globalization.CultureInfo.InvariantCulture))</div>
	</div>
	
	<div id="darecontainer">
		<p id="daretext">
        @(Model.Description)
	    </p>
	</div>

    
	<div class="sectionHeader">Ready to take this dare?</div>

    @{
        if (Model.TargetCustomer != null)
        {
	        <h4>This dare is only for @(Model.TargetCustomer.FirstName).</h4>

            switch (Model.TargetCustomer.ForeignUserType)
            {
                case (int)DareyaAPI.Models.Customer.ForeignUserTypes.Facebook:
                    <p>Is that you? Authenticate with Facebook and get started.</p>
                    <p>@Html.ActionLink("Authenticate with Facebook", "AuthorizeFacebook", "Onboard")</p>
                  break;
                case (int)DareyaAPI.Models.Customer.ForeignUserTypes.Twitter:
                    <p>Is that you? Authenticate with Twitter and get started.</p>
                    <p>@Html.ActionLink("Authenticate with Twitter", "AuthorizeTwitter", "Onboard")</p>
                  break;
            }
            
            <p>Already connected with <em>dareme.to</em>? Accept this dare in the <em>dareme.to</em> app on your iPhone.</p>
        }
        else
        {
            <p>Create a <em>dareme.to</em> account in seconds and take your shot at earning $@(Model.CurrentBid.ToString("0.00", System.Globalization.CultureInfo.InvariantCulture)).</p>
            using (Html.BeginForm("Signup", "Onboard"))
            {
                <input type="hidden" name="ChallengeID" value="@(Model.ID)" />
                
                <label for="FirstName">First Name:</label>
			    <input type="text" name="FirstName" />
			    <label for="LastName">Last Name:</label>
			    <input type="text" name="LastName" />
			    <label for="EmailAddress">Email Address:</label>
			    <input type="text" name="EmailAddress" />
			    <label for="Password">Desired Password:</label>
			    <input type="password" name="Password" />
			    
			    <input class="btn btn-success" type="submit" value="Sign Up" />
            }
        }
        }

</div>

	